// <auto-generated />
using System;
using ControlFinanzasProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlFinanzasProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251115052921_CambiarFechasPorDiasEnTarjetaCredito")]
    partial class CambiarFechasPorDiasEnTarjetaCredito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlFinanzasProject.Models.CategoriaMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("TipoMovimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EsActivo");

                    b.HasIndex("TipoMovimientoId");

                    b.ToTable("CategoriaMovimiento");
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaMovimientoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EsEfectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoAnterior")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoPosterior")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TarjetaCreditoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaMovimientoId");

                    b.HasIndex("EsActivo");

                    b.HasIndex("EsEfectivo");

                    b.HasIndex("Fecha");

                    b.HasIndex("TarjetaCreditoId");

                    b.HasIndex("CategoriaMovimientoId", "EsActivo");

                    b.HasIndex("Fecha", "EsActivo");

                    b.ToTable("Movimiento", t =>
                        {
                            t.HasCheckConstraint("CK_Movimiento_Monto", "[Monto] > 0");
                        });
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.PagoTarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("int");

                    b.Property<int>("TarjetaCreditoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaPago");

                    b.HasIndex("MovimientoId")
                        .IsUnique();

                    b.HasIndex("TarjetaCreditoId");

                    b.ToTable("PagoTarjeta", t =>
                        {
                            t.HasCheckConstraint("CK_PagoTarjeta_MontoPago", "[MontoPago] > 0");
                        });
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.TarjetaCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DeudaActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiaCorte")
                        .HasColumnType("int");

                    b.Property<int>("DiaPago")
                        .HasColumnType("int");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("LimiteCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EsActivo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TarjetaCredito", t =>
                        {
                            t.HasCheckConstraint("CK_TarjetaCredito_DeudaActual", "[DeudaActual] >= 0 AND [DeudaActual] <= [LimiteCredito]");
                        });
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.TipoMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("TipoMovimiento");
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.CategoriaMovimiento", b =>
                {
                    b.HasOne("ControlFinanzasProject.Models.TipoMovimiento", "TipoMovimiento")
                        .WithMany("CategoriaMovimientos")
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.Movimiento", b =>
                {
                    b.HasOne("ControlFinanzasProject.Models.CategoriaMovimiento", "CategoriaMovimiento")
                        .WithMany("Movimientos")
                        .HasForeignKey("CategoriaMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlFinanzasProject.Models.TarjetaCredito", "TarjetaCredito")
                        .WithMany("GastosCredito")
                        .HasForeignKey("TarjetaCreditoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaMovimiento");

                    b.Navigation("TarjetaCredito");
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.PagoTarjeta", b =>
                {
                    b.HasOne("ControlFinanzasProject.Models.Movimiento", "Movimiento")
                        .WithOne()
                        .HasForeignKey("ControlFinanzasProject.Models.PagoTarjeta", "MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlFinanzasProject.Models.TarjetaCredito", "TarjetaCredito")
                        .WithMany("Pagos")
                        .HasForeignKey("TarjetaCreditoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movimiento");

                    b.Navigation("TarjetaCredito");
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.CategoriaMovimiento", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.TarjetaCredito", b =>
                {
                    b.Navigation("GastosCredito");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ControlFinanzasProject.Models.TipoMovimiento", b =>
                {
                    b.Navigation("CategoriaMovimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
